name: 'sports-club-management-system Playwright Tests'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests against'
        required: true
        type: environment
        default: prod
  
permissions:
  pages: write
  id-token: write

jobs:
  e2e-tests:

    #select the machine to run the tests against
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
      options: --user 1001
  
    environment: ${{ github.event.inputs.environment }}

    env:
      USER:  ${{ vars.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL_WEB: ${{ vars.BASE_URL_WEB }} 
      BASE_URL_API: ${{ vars.BASE_URL_API }}
  
    steps:
      - name: check environment variables content
        run: | #it sets multiple lines for the echo command
          echo "The environment is $environment"
          echo "Base URL web is $BASE_URL_WEB"
          echo "Base URL API is $BASE_URL_API"
          echo "USER is $USER"

      # Checkout code    
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Install dependencies    
      - name: Install dependencies
        run: npm ci

      # Install Playwright Browsers  
      - name: Install Playwright Browsers
        run: npx playwright install chromium firefox

      # Run Playwright tests  
      - name: Run Playwright tests
        run: npm run ui-challenge-workflow-tests || true

      # upload html report results
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: playwright-report/index.html  
          retention-days: 1

      # Configure GitHub Pages
      - uses: actions/configure-pages@v5 # upload test results

      # Upload the HTML report as a GitHub Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

      # Deploy the HTML report to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show Report URL
        if: ${{ !cancelled() && steps.deployment.outcome == 'success' }} 

        run: |   
          echo "📌 Playwright HTML Report: ${{ steps.deployment.outputs.page_url }}"
